### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by mmattioli**
Added Godoc badge/link for easy access to the documentation

Minor grammatical improvement

Fixed broken markdown link to libnl

### CODE REVIEW

**Comment by mmattioli** [comment]
@baptr @4a6f656c any comments/opinions on this PR?

**Comment by mmattioli** [comment]
@baptr @4a6f656c *bump*

**Comment by mmattioli** [comment]
@baptr @4a6f656c *bumpidy bump*

**Comment by baptr** [comment]
Sorry for the delay. Thanks for the cleanup!

**Pull request merged**
