### PR TITLE
Introduce build inside the docker

### PR DESCRIPTION
**Pull request by onorua**
This should simplify adoption by the community, and may save couple of
hours for new users who would like to just try the tool without
additional efforts.

### CODE REVIEW

**Comment by onorua** [comment]
I signed it!

**Comment by ibakirov** [comment]
I suggest to use FROM debian:jessie rather than FROM ubuntu:* in this dockerfile, to be far away from any Canonical's IP Policy speculations...

**Comment by onorua** [comment]
If that the reason to don't merge - I'll update the base image. Many projects use Ubuntu as base image which makes it better candidate to prevent downloading of the underlying layers.

**Comment by bwahn** [comment]
If seesaw run in docker, It may be would better add some command and explanation. For example, It may use like "$ docker run -d seesaw". @onorua Do you have some idea?

**Comment by ibakirov** [comment]
> $ docker run -d seesaw
can be done after Dockerfile accepted and official image on Hub published

**Comment by onorua** [comment]
I do not run seesaw in the docker, I do build of the packages without necessary installing anything on your host. That is why I call it "hack" the same way as kubernetes has it, if you want to hack around, you need to be able to build it. But I can work on running the seesaw inside the docker as well, if there is a need. 
But this most probably be another pull request.

**Pull request closed without merging**
